name: Python application

on:
  schedule:
    - cron: '3-59/10 * * * *'
  workflow_dispatch:

permissions:
  contents: read

env:
  STATE_FILE: './appstate'

jobs:
  exec:
    runs-on: ubuntu-latest
    steps:
      - name: actions/cache用keyの生成
        run: echo "APPSTATE_KEY=$(date +%s)" >> "$GITHUB_ENV"

      - uses: actions/cache@v3
        id: appstate
        with:
          path: ${{ env.STATE_FILE }}
          key: appstate-${{ env.APPSTATE_KEY }} # 毎回、最新のキャッシュを保存するためにIDを指定する
          restore-keys: appstate- # 復元時は最新のキャッシュを指定する

      - name: 初回ならキャッシュファイルを初期化
        run: |
          if [ ! -f ${{ env.STATE_FILE }} ]; then
            echo '0' > ${{ env.STATE_FILE }}
          fi
      - run: cat ${{ env.STATE_FILE }}

      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install feedparser pydantic tweepy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Exce App
        env:
          FEED_URL: ${{ vars.FEED_URL }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
        run: |
          python main.py
