name: GitHub Secrets Demo
on:
  schedule:
    - cron: '3-59/10 * * * *'
jobs:
  GitHub-Secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Secrets
        shell: bash
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        run: |
          echo -e "secrets.TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}\\n\$TWITTER_API_KEY $TWITTER_API_KEY"
